### ISSUE TITLE
COM_USERS_EMAIL_PASSWORD_RESET_BODY

### ISSUE THREAD

**Issue by dmitrkov** [Joomla-Ukraine/uk-UA-3.x#1]
Изменился процесс восстановления пароля. Теперь текст должен содержать 3 строковые переменные.
Например так:
"Вітаємо!\n\nНа сайті %s був зроблений запит на відновлення пароля до вашого облікового запису. Щоб відновити пароль, Вам необхідно ввести вказаний нижче код підтвердження.\n\nКод підтвердження: %s\n\nДля введення коду підтвердження перейдіть на сторінку за посиланням нижче.\n\n %s\n\nДякуємо!"

**Comment by evolvens** [comment]
Дякую.
Врахуємо під час локалізації!
